bundler_args: --without guard metrics
script: "bundle exec rake spec"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
  - jruby
  - rbx
  - rbx-2.0
env:
  - JRUBY_OPTS="--1.8"
  - JRUBY_OPTS="--1.9"
matrix:
  exclude:
    - rvm: 1.8.7
      env: JRUBY_OPTS="--1.9"
    - rvm: 1.8.7
      env: JRUBY_OPTS="--1.8"
    - rvm: 1.9.2
      env: JRUBY_OPTS="--1.9"
    - rvm: 1.9.3
      env: JRUBY_OPTS="--1.9"
    - rvm: ruby-head
      env: JRUBY_OPTS="--1.9"
    - rvm: ree
      env: JRUBY_OPTS="--1.9"
    - rvm: rbx
      env: JRUBY_OPTS="--1.9"
    - rvm: rbx-2.0
      env: JRUBY_OPTS="--1.9"
