---
AbcMetricMethodCheck:            { score: 13 }
AssignmentInConditionalCheck:    { }
CaseMissingElseCheck:            { }
ClassLineCountCheck:             { line_count: 161 }
ClassNameCheck:                  { pattern: !ruby/regexp /\A[A-Z][a-z](?:[A-Z]?[a-z])+\z/ }
ClassVariableCheck:              { }
CyclomaticComplexityBlockCheck:  { complexity: 2 }
CyclomaticComplexityMethodCheck: { complexity: 8 }
EmptyRescueBodyCheck:            { }
ForLoopCheck:                    { }
# TODO: decrease line_count to 10 or less
MethodLineCountCheck:            { line_count: 14 }
MethodNameCheck:                 { pattern: !ruby/regexp /\A(?:[a-z](?:_?[a-z])+[?!]?|\[\]|==|<=>|[+*&|-])\z/ }
ModuleLineCountCheck:            { line_count: 163 }
ModuleNameCheck:                 { pattern: !ruby/regexp /\A[A-Z][a-z](?:[A-Z]?[a-z])+\z/ }
ParameterNumberCheck:            { parameter_count: 3 }
