AssignmentInConditionalCheck:    { }
CaseMissingElseCheck:            { }
ClassLineCountCheck:             { line_count: 225 }
ClassNameCheck:                  { pattern: !ruby/regexp /\A[A-Z][a-z](?:[A-Z]?[a-z])+\z/ }
ClassVariableCheck:              { }
CyclomaticComplexityBlockCheck:  { complexity: 4 }
# TODO: decrease complexity to 8 or less
CyclomaticComplexityMethodCheck: { complexity: 9 }
EmptyRescueBodyCheck:            { }
ForLoopCheck:                    { }
# TODO: decrease line_count to 10 or less
MethodLineCountCheck:            { line_count: 24 }
# TODO: get "default" roodi.yml to include "&" in regexp
MethodNameCheck:                 { pattern: !ruby/regexp /^[_a-z<>=\[&|+-\/\*`]+[_a-z0-9_<>=~@\[\]]*[=!\?]?$/ }
ModuleLineCountCheck:            { line_count: 229 }
ModuleNameCheck:                 { pattern: !ruby/regexp /\A[A-Z][a-z](?:[A-Z]?[a-z])+\z/ }
ParameterNumberCheck:            { parameter_count: 3 }
