---
AbcMetricMethodCheck:            { score: 10 }
AssignmentInConditionalCheck:    { }
CaseMissingElseCheck:            { }
ClassLineCountCheck:             { line_count: 137 }
ClassNameCheck:                  { pattern: !ruby/regexp /\A[A-Z][a-z](?:[A-Z]?[a-z])+\z/ }
ClassVariableCheck:              { }
CyclomaticComplexityBlockCheck:  { complexity: 2 }
CyclomaticComplexityMethodCheck: { complexity: 8 }
EmptyRescueBodyCheck:            { }
ForLoopCheck:                    { }
# TODO: decrease line_count to 5 to 10
MethodLineCountCheck:            { line_count: 14 }
MethodNameCheck:                 { pattern: !ruby/regexp /\A(?:[a-z](?:_?[a-z])+[?!]?|\[\]=?|==|<=>|[+*&|-])\z/ }
ModuleLineCountCheck:            { line_count: 141 }
ModuleNameCheck:                 { pattern: !ruby/regexp /\A[A-Z][a-z](?:[A-Z]?[a-z])+\z/ }
# TODO: decrease parameter_count to 2 or less
ParameterNumberCheck:            { parameter_count: 3 }
